/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GestionRouteImport } from './routes/gestion'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as ProyectoRouteImport } from './routes/proyecto'
import { Route as SimuladorRouteImport } from './routes/simulador'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionRoute = GestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoRoute = ProyectoRouteImport.update({
  id: '/proyecto',
  path: '/proyecto',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gestion': typeof GestionRoute
  '/inteligencia': typeof InteligenciaRoute
  '/proyecto': typeof ProyectoRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gestion': typeof GestionRoute
  '/inteligencia': typeof InteligenciaRoute
  '/proyecto': typeof ProyectoRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gestion': typeof GestionRoute
  '/inteligencia': typeof InteligenciaRoute
  '/proyecto': typeof ProyectoRoute
  '/simulador': typeof SimuladorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gestion' | '/inteligencia' | '/proyecto' | '/simulador'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gestion' | '/inteligencia' | '/proyecto' | '/simulador'
  id:
    '__root__' | '/' | '/gestion' | '/inteligencia' | '/proyecto' | '/simulador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GestionRoute: typeof GestionRoute
  InteligenciaRoute: typeof InteligenciaRoute
  ProyectoRoute: typeof ProyectoRoute
  SimuladorRoute: typeof SimuladorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion': {
      id: '/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof GestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto': {
      id: '/proyecto'
      path: '/proyecto'
      fullPath: '/proyecto'
      preLoaderRoute: typeof ProyectoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GestionRoute: GestionRoute,
  InteligenciaRoute: InteligenciaRoute,
  ProyectoRoute: ProyectoRoute,
  SimuladorRoute: SimuladorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
